version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tdv-scraper
    container_name: TdV-scraper
    env_file:
      - .env
    ports:
      - '8080:3000'
    # restart: unless-stopped
