version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tdv-api
    container_name: tdV-teste
    env_file:
      - .env
    ports:
      - '8080:8080'
    # restart: unless-stopped
